#!/sbin/sh

echo "Make sure /vendor partition is mounted"

# Wifi
   wifirc=`grep -H -r "/vendor/bin/hw/wpa_supplicant" /vendor/etc/init/hw/* | cut -d: -f1`
    sed -i "s|service wpa_supplicant /vendor/bin/hw/wpa_supplicant|service vendor.wpa_supplicant /vendor/bin/hw/wpa_supplicant|g" $wifirc
	
# NFC
if [ -e "/vendor/etc/libnfc-brcm.conf" ]; then
    mv /vendor/etc/libnfc-brcm.conf /vendor/etc/libnfc-nci.conf
    sed -i '/APPL_TRACE_LEVEL/d' /vendor/etc/libnfc-nci.conf
    sed -i '/PROTOCOL_TRACE_LEVEL/d' /vendor/etc/libnfc-nci.conf
    sed -i '/MAX_RF_DATA_CREDITS/d' /vendor/etc/libnfc-nci.conf
    echo "NFC_DEBUG_ENABLED=0" >> /vendor/etc/libnfc-nci.conf
fi

# Cleanup overlays
mv /vendor/overlay/framework-res__auto_generated_rro.apk /vendor/overlay/framework-res__auto_generated_rro.apk2
rm -rf /vendor/overlay/*.apk
mv /vendor/overlay/framework-res__auto_generated_rro.apk2 /vendor/overlay/framework-res__auto_generated_rro.apk

# Bluetooth Audio
initrc= /vendor/init/hw/init*
echo "mount none /vendor/lost+found /vendor/etc/audio bind" $initrc

#Cleanup overlays
mv /vendor/overlay/framework-res__auto_generated_rro.apk /vendor/overlay/framework-res__auto_generated_rro.apk2
rm -rf /vendor/overlay/*.apk
mv /vendor/overlay/framework-res__auto_generated_rro.apk2 /vendor/overlay/framework-res__auto_generated_rro.apk

# Biometrics
fphal=`ls /vendor/bin/hw/android.hardware.biometrics.fingerprint*`
if grep -Fxq "_ZN7android16IKeystoreService11asInterfaceERKNS_2spINS_7IBinderEEE" $fphal
then
    sed -i "s/libkeystore_binder.so/libWkeystorebinder.so/" $fphal
fi

# Speed up fp enroll
biometrics_rc= /vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service*
if grep -Fxq "writepid /dev/cpuset/system-background/tasks" $biometrics_rc
then
    sed -i '/writepid /dev/cpuset/system-background/tasks/d'$biometrics_rc
fi

# LG RIL
if [ -e "/vendor/lib64/vendor.lge.hardware.radio@1.0.so" ]; then
    sed -i "s/android.hardware.radio@1.0.so/Wndroid.hardware.radio@1.0.so/" /vendor/lib/vendor.lge.hardware.radio@1.0.so
    sed -i "s/android.hardware.radio@1.0.so/Wndroid.hardware.radio@1.0.so/" /vendor/lib64/vendor.lge.hardware.radio@1.0.so
fi

# Moto RIL
if [ -e "/vendor/lib64/libsensorndkbridge.so" ]; then
    sed -i "s/android.hardware.sensors@1.0.so/Wndroid.hardware.sensors@1.0.so/" /vendor/lib/libsensorndkbridge.so
    sed -i "s/android.hardware.sensors@1.0.so/Wndroid.hardware.sensors@1.0.so/" /vendor/lib64/libsensorndkbridge.so
fi

# Motorola camera
if [ -e "/vendor/lib/libjustshoot.so" ]; then
    sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/lib/libjustshoot.so
    sed -i "s/libutils.so/libWtils.so/" /vendor/lib/libjustshoot.so
fi
if [ -e "/vendor/lib/lib_motsensorlistener.so" ]; then
    sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/lib/lib_motsensorlistener.so
fi
if [ -e "/vendor/lib/libmot_gpu_mapper.so" ]; then
    sed -i "s/libgui.so/libWui.so/" /vendor/lib/libmot_gpu_mapper.so
    sed -i "s/libui.so/libWi.so/" /vendor/lib/libmot_gpu_mapper.so
    sed -i "s/libutils.so/libWtils.so/" /vendor/lib/libmot_gpu_mapper.so
fi

# Whyred camera
if [ -e "/vendor/lib/libvidhance_gyro.so" ]; then
    sed -i "s/android.frameworks.sensorservice@1.0.so/Wndroid.frameworks.sensorservice@1.0.so/" /vendor/lib/libvidhance_gyro.so
fi
if [ -e "/vendor/lib/libMiWatermark.so" ]; then
    if grep -Fxq "_ZN6icu_5811StringPieceC1EPKc" /vendor/lib/libMiWatermark.so
    then
        sed -i "s/libminikin.so/libWinikin.so/" /vendor/lib/libMiWatermark.so
        sed -i "s/libicuuc.so/libWcuuc.so/" /vendor/lib/libMiWatermark.so
    fi
fi

# Tissot and Sagit camera
if [ -e "/vendor/lib/libMiCameraHal.so" ]; then
    sed -i "s/libminikin.so/libWinikin.so/" /vendor/lib/libMiCameraHal.so
    sed -i "s/libicuuc.so/libWcuuc.so/" /vendor/lib/libMiCameraHal.so
fi

# OP5(t) fingerprint
if [ -e "/sys/project_info/project_name" ]; then
    device=`cat /sys/project_info/project_name`
    if [[ $device = "17801" ]]; then
        if [ -e "/sys/devices/soc/soc:fingerprint_detect/sensor_version" ]; then
            fingerp=`cat /sys/devices/soc/soc:fingerprint_detect/sensor_version`
            if [[ $fingerp = "3" ]]; then
                mv /vendor/lib64/hw/fingerprint.goodix.so /vendor/lib64/hw/fingerprint.qcom.so
            else
                mv /vendor/lib64/hw/fingerprint.fpc.so /vendor/lib64/hw/fingerprint.qcom.so
            fi
        fi
    fi
fi

# Payton Camera
if [ -e "/vendor/lib/hw/camera.sdm660.so" ]; then
    if grep -Fxq "_ZN7android9StopWatchC1EPKcij" /vendor/lib/hw/camera.sdm660.so
    then
        sed -i "s/libutils.so/libWtils.so/" /vendor/lib/hw/camera.sdm660.so
    fi
fi

exit 0














